-- Which weighing instrument produced the reading a sold-by-weight line was priced on.
--
--   Weights and Measures Act 1985 s.11   selling by weight on an instrument not passed as fit for
--                                        use for trade is an offence
--
-- The till has sold by weight from "the reading the approved scale shows" since 816640d, and never
-- said which scale. tenant-svc now keeps the register of instruments and their verification
-- history, and the till refuses to sell by weight from one that is not certified. The line records
-- the instrument it was weighed on, so an inspector can go from a receipt to a certificate.
-- Null for a line sold by the each, and for lines sold before this existed.
ALTER TABLE order_items ADD COLUMN weighing_instrument_id UUID;
