# reporting-svc — defaults (local dev).
shelfj.service.name=reporting-svc
server.port=8012
server.host=0.0.0.0

shelfj.db.url=jdbc:postgresql://localhost:5432/shelfj
shelfj.db.user=reporting_svc
shelfj.db.password=reporting_dev_change_me
shelfj.db.schema=reporting

shelfj.consul.enabled=true
shelfj.consul.host=localhost
shelfj.consul.port=8500

shelfj.kafka.enabled=true
shelfj.kafka.bootstrap=localhost:9092

otel.sdk.disabled=false
otel.service.name=reporting-svc
otel.traces.exporter=zipkin
otel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans
