apiVersion: 1

datasources:
  # ── Metrics ────────────────────────────────────────────────────────────────
  - name: Prometheus
    type: prometheus
    uid: prometheus-shelfj
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
      prometheusType: Prometheus
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo-shelfj

  # ── Logs ───────────────────────────────────────────────────────────────────
  - name: Loki
    type: loki
    uid: loki-shelfj
    url: http://loki:3100
    access: proxy
    editable: false
    jsonData:
      maxLines: 5000
      derivedFields:
        - datasourceUid: tempo-shelfj
          matcherRegex: '"traceId":"(\w+)"'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View in Tempo"

  # ── Traces ─────────────────────────────────────────────────────────────────
  - name: Tempo
    type: tempo
    uid: tempo-shelfj
    url: http://tempo:3200
    access: proxy
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus-shelfj
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki-shelfj
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
      spanBar:
        type: "Tag"
        tag: "http.path"
